services:
  - postgresql
addons:
  postgresql: "9.6"
language: node_js
node_js:
  - "stable"
install:
  - npm install
before_script:
  - psql -c 'create database freementors;' -U postgres
script:
  - npm test
after_success:
  - npm run coveralls